package harmony.communityservice.common.outbox;

public enum InnerEventType {
    DELETED_CATEGORY,
    DELETED_BOARD_IN_CHANNEL,
    DELETED_BOARD_IN_CHANNELS,
    CREATED_CHANNEL,
    DELETED_CHANNEL,
    DELETED_COMMENT_IN_BOARD,
    DELETED_COMMENT_IN_BOARDS,
    DELETED_EMOJI_IN_BOARD,
    DELETED_EMOJI_IN_BOARDS,
    CREATED_GUILD,
    DELETED_GUILD,
    CREATED_USER
}
